### ISSUE TITLE
Link effect

### ISSUE THREAD

**Issue by Eslem** [Eslem/GameStore-Sass#1]
.brackets-link{
    a{
        &::before, &::after{
            display: inline-block;
            opacity: 0;
            transition(transform 0.3s, opacity 0.2s);  
        }
        &::before{
            margin-right: 10px;
            content: '[';
            transform(translateX(20px));
        }
        &::after{
            margin-left: 10px;
            content: ']';
            transform(translateX(-20px));
        }
        &:hover::before,
        &:hover::after,
        &:focus::before,
        &:focus::after{
            opacity: 1;
            transform(translateX(0px));
        }
    }
}

**Comment by hermanu** [comment]
/*scss */

#header-categorias {
    display:none;
}

#menu-header{  
    li{
        &::before, &::after{
            display: inline-block;
            opacity: 0;
            color: white;
            @include transition2(transform 0.3s, opacity 0.2s);

```
    }
    &::before{
        margin-right: 10px;
        content: '[';
        transform: translateX(20px);
    }
    &::after{
        margin-left: 10px;
        content: ']';
        transform: translateX(-20px);
    }
    &:hover::before,
        &:hover::after,
        &:focus::before,
        &:focus::after{
        opacity: 1;
        transform: translateX(0px);
    }        

}
```

}

/\* html */ 

  <div class="navbar invisible" id="menu-header">

```
        <img src="images/logo1.png" alt="logo" class="logo">

        <ul id="lista-menu">
            <li id="menu-home"><a href="#">Home</a></li>
            <li id="menu-categorias"><a href="#">Categorias</a>
                <ul id="header-categorias"></ul>
            </li>
            <li id="menu-perfil"><a href="#">Perfil</a></li>  
            <li class="slide-nav"><i class="fa fa-bars"></i></li>
        </ul>
        <form class="navbar-form navbar-right">
            <input type="text" class="form-slideLeft" placeholder="Login">
            <input type="text" class="form-slideLeft" placeholder="Password">
            <div class="hexagon navbar-right show-animate inactive">
                <i class="fa fa-sign-in"></i>
            </div>

        </form>
    </div>
```
